# Site settings
title: Developer Center
email: developers@illumineto.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; 2015 Illumineto, LLC. | <a href="www.illumineto.com" target="_blank">Policies</a> | <a href="www.illumineto.com" target="_blank">Compliance</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://developer.illumineto.com" # the base hostname & protocol for your site
twitter_username: illumineto
github_username:  illumineto
permalink: /blog/:categories/:title.html

# Build settings
markdown: kramdown
